# 5.1 Python Numpy

- Numpy is a general-purpose array-processing package. 
- It provides a high-performance multidimensional array object,  and tools for working with these arrays. 
- It is the fundamental package for scientific computing (like Physics, Data Science, Computer-graphics etc)
- It's used in many scientifc area like PHYSICS, Mathematics etc

#### NumPy Arrays

##### python objects
1. high-level number objects: integers, floating point
2. container: list(costless insertion and append), dictnaries(fast lockup)

###### Numpy (aka: array oriented computing) provides:
1. Extension packages for: Multidimesional array
2. closer to hardware(efficiency)
3. designed for scientific calculation

In [1]:
#Two simple way to create an arrray 

import numpy as np

#first one
a = np.array([0,1,2,3])
print(a)

#Second one
print(np.arange(6))


[0 1 2 3]
[0 1 2 3 4 5]


#### why Numpy?:  It's Super fast baby!! look here

In [2]:
#python list
L = range(1000)                       #L = [0,1,2,....,999]
print(L)
%timeit [i**2 for i in L]

range(0, 1000)
228 µs ± 18.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [75]:
#NumPy 
a = np.arange(1000)
print(a)
a.ndim
%timeit a**2    

1.54 µs ± 138 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# --

# 1. CREATING ARRAYS

##### 1.1 Manual construction of array

In [4]:
#1-D  (called Vector)

a = np.array([0,1,2,2])

a

array([0, 1, 2, 2])

In [5]:
#print Dimension
a.ndim


1

In [6]:
a.shape

(4,)

In [7]:
a.size

4

In [8]:
#2-d  (Matrix) , 3-d ,...(tensor)

b= np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b.ndim

2

In [10]:
b.shape

(2, 3)

In [11]:
b.size

6

In [12]:
len(b)    #return the size of first dimesion

2

In [13]:
c = np.array([[[0,1],[2,3],[4,5],[6,7]]])
c
            

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [14]:
c.ndim

3

In [15]:
c.size

8

In [16]:
c.shape

(1, 4, 2)

###### Note

##### 1D array---> Vector
##### 2D array---> Matrix
##### nD array---> Tensor
- Tensorflow is somewhats related to tensor

### 1.2 Function for creating arrays

In [17]:
# using arange function      : an array-valued verson of python range function

a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b = np.arange(1,20,2)       #(start, stop, stepsize)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
#using linspace

a = np.linspace(0,1,6)      #(start,  stop  ,  no of points)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

#### common array
- Identity
- zeros
- ones..etc

In [20]:
#common array

x= np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
#lly
y= np.zeros((4,4))
y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
z= np.eye(3,2)
z

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [24]:
# Creating matrix using diag  function

m = np.diag([2,4,333,4,4,4,4])
m

array([[  2,   0,   0,   0,   0,   0,   0],
       [  0,   4,   0,   0,   0,   0,   0],
       [  0,   0, 333,   0,   0,   0,   0],
       [  0,   0,   0,   4,   0,   0,   0],
       [  0,   0,   0,   0,   4,   0,   0],
       [  0,   0,   0,   0,   0,   4,   0],
       [  0,   0,   0,   0,   0,   0,   4]])

In [25]:
np.diag(m)   #prining the diagnal

array([  2,   4, 333,   4,   4,   4,   4])

In [26]:
# Creating matrix using random


q = np.random.rand(4)   
q

array([0.35554156, 0.34318316, 0.82004507, 0.53439685])

In [27]:
k = np.random.randn(4)         #Gausion normal 
k                             #will learn in probality and statistics chapter

array([ 1.42220173, -0.40678947, -1.27483339,  1.70969893])

# --

# 2. Basic DataTypes

In [28]:
a = np.arange(10)
a.dtype

dtype('int32')

In [29]:
# you can explicitly specify types of datatypes you want
a = np.arange(10, dtype = 'float64')
a.dtype

dtype('float64')

In [30]:
#Default dtype of ones and zeros is:  float 

s= np.zeros((4,4))
print(s)
s.dtype

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


dtype('float64')

### other datatype

In [31]:
#complex datatype
d = np.array([1+2j, 2+ 5j])   
d.dtype

dtype('complex128')

In [32]:
#Boolean datatype

b = np.array([True,False,False, False, True ])
print(b)
b.dtype

[ True False False False  True]


dtype('bool')

In [33]:
# string datatype
s = np.array(['Faizan', 'Imran', 'Rizwan'])
print(s)
s.dtype

['Faizan' 'Imran' 'Rizwan']


dtype('<U6')

# --

# 3. Indexing and Slicing

#### 3.1 Indexing

The items of an array can be accessed and assigned to the same way as python sequences
(eg. list)

In [34]:
e = np.arange(1,10, 2)

print(e[4])

9


In [35]:
# for multidimensional arrays, indexes are tuples of integrs:
a = np.diag([2,3,4,5,6,7])
print(a[2,2])
print(a)


4
[[2 0 0 0 0 0]
 [0 3 0 0 0 0]
 [0 0 4 0 0 0]
 [0 0 0 5 0 0]
 [0 0 0 0 6 0]
 [0 0 0 0 0 7]]


In [36]:
#assigning values:
a[2,2] = 400000
print(a)

[[     2      0      0      0      0      0]
 [     0      3      0      0      0      0]
 [     0      0 400000      0      0      0]
 [     0      0      0      5      0      0]
 [     0      0      0      0      6      0]
 [     0      0      0      0      0      7]]


### 3.2 Slicing

In [37]:
u = np.arange(1,20,2)
print(u[3:5])

[7 9]


In [38]:
f = np.arange(10)               #example2
print(f)

f[1:8:2]          # [ startindex:   endindex(exclusive) : steps)

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7])

In [39]:
# we can also combine assignmnet and slicing:

a = np.arange(10)
print(a)

a[5:] = 1000
print(a)

[0 1 2 3 4 5 6 7 8 9]
[   0    1    2    3    4 1000 1000 1000 1000 1000]


In [45]:
b = np.arange(5)
a[5:]= b[::-1]       #-1 : steping reverse order  #we used uperwala  a
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# --

# 4. Copies and Views

In [57]:
ab = np.arange(10)

c = ab[::2]
c

array([0, 2, 4, 6, 8])

In [58]:
c[0] =10
print(ab)
np.shares_memory(ab,c)

[0 1 2 3 4 5 6 7 8 9]


False

In [60]:
# using copy :  same code only added 
ab = np.arange(10)

c = ab[::2].copy()     #  .copy()   forcing
print(c)


[0 2 4 6 8]


In [61]:
c[0] =10
print(ab)    #will remain same
np.shares_memory(ab,c)

[0 1 2 3 4 5 6 7 8 9]


False

# --

# 5. Fancy Indexing

In [62]:
a = np.random.randint(0,20,15)        #(start:  end  :  quantity)
a

array([ 9,  6, 16,  5,  0,  2, 16,  0,  8, 14,  1, 17,  2, 19, 12])

In [66]:
mask = (a%2==0)
b = a[mask]       #we can ceate a subset using    a[mask]
b

array([-400, -400, -400, -400, -400, -400, -400, -400, -400, -400])

###### indexing with mask  can be very usefull to assign value to a sub array:

In [70]:
a[mask]= -400      #it will substitute -400 everyindex where mask operates
print(a)

[   9 -400 -400    5 -400 -400 -400 -400 -400 -400    1   17 -400   19
 -400]


##### indexing with an array of integer 

In [72]:
 g = np.arange(0,100,10)
print(g)

[ 0 10 20 30 40 50 60 70 80 90]


In [73]:
h = g[[2,3,2,4,2]]
print(h)

[20 30 20 40 20]


In [74]:
# new value can be assigned 

g[[9,7]] = -3
g

array([ 0, 10, 20, 30, 40, 50, 60, -3, 80, -3])

# --

#### Quick Recap
- contents 
1. creating an array
2. Basic DataTypes
3. Indexing and slicing
4. copy and view
5. Fancy indexing and using    [mask]